### ISSUE TITLE
CapsLock+Shift (Shift+CapsLock) also switches language

### ISSUE THREAD

**Issue by NikitaTopsky** [erryox/Switchy#13]
CapsLock+Shift or Shift+CapsLock should only have the action of activating the CapsLock button. But the keyboard layout also changes. 
This bug only exists with an argument nopopup.
Can you fix this?

**Comment by 1280px** [comment]
Can't replicate on the latest version of code. It seems the issue is only present for the latest release (which is built on an older codebase) and earlier.

**Comment by erryox** [comment]
Hey,

I've rebuilt the program with the latest changes, and everything should be ok now. Please try release [1.4.3](https://github.com/erryox/Switchy/releases/tag/1.4.3) and see if it works for you.
