### ISSUE TITLE
Caps Lock does not turn off

### ISSUE THREAD

**Issue by deadmd** [erryox/Switchy#5]
Windows 10 is configured to cancel CapsLock mode when Shift is pressed, switching languages is only Win + Space, and Switchy starts up. When you press the Shift + CapsLock combination (and it's easy to accidentally press, missing one of the keys), CapsLock mode is activated, which cannot be turned off from the keyboard until the Switchy process is stopped through the task manager.

If CapsLock turns on when you press Shift + CapsLock, you need to turn it off when you press the same combination again.

**Comment by erryox** [comment]
To achieve the behavior you want, you can configure to cancel CapsLock mode with the CapsLock key, not the Shift key.
