### ISSUE TITLE
ru-en only

### ISSUE THREAD

**Issue by wincmd64** [erryox/Switchy#6]
добавь ini к проге с параметром ru-en only 1\0

**Comment by online** [comment]
У меня в системе три раскладки: en, ru и ua. Хотелось бы иметь возможность по нажатию на Caps Lock переключать либо между en / ru, либо en / ua.

Это вообще реально?

**Comment by erryox** [comment]
По сути, всё, что делает программа - эмулирует нажатие клавиш Win+Space или Alt+Shift. Так что в рамках текущей реализации это добавить не так просто. Быть может когда-то в будущем я к этому вернусь и добавлю такую возможность. Но я довольно давно не обновлял этот проект, так что скорее всего не в ближайшее время.
