### ISSUE TITLE
can't find program process

### ISSUE THREAD

**Issue by ITilyaGO** [erryox/Switchy#8]
I don’t understand what process the program creates, it’s not visible in the task manager, I would like to know what it’s called, and also have a combination of keys to fucking exit the program

**Comment by 1280px** [comment]
It doesn't create any additional processes, and the program's process name is the same as its .exe file name (`Switchly.exe` by default)

P.s. Use Process Hacker, it allows searching processes by its name; Windows Task Manager is very limited anyway, so no reason to not use it.
